config/routes.rb
CustomSurveyApp::Application.routes.draw do
  resources :survey_types

  resources :submission_entries

  resources :submissions

  devise_for :users

  resources :answers

  resources :questions

  resources :survey_records
  
  get "/home/survey_session"
  
  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end
  
  get "/home/error_survey"

  
    get "/:name" => "home#survey_session"
  
   root :to => 'home#survey_view'

end

app/controllers/survey_types_controller.rb
class SurveyTypesController < ApplicationController
  
  load_and_authorize_resource
     before_filter :auth_user

  
  # GET /survey_types
  # GET /survey_types.json
  def index
    @survey_types = SurveyType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @survey_types }
    end
  end

  # GET /survey_types/1
  # GET /survey_types/1.json
  def show
    @survey_type = SurveyType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey_type }
    end
  end

  # GET /survey_types/new
  # GET /survey_types/new.json
  def new
    @survey_type = SurveyType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey_type }
    end
  end

  # GET /survey_types/1/edit
  def edit
    @survey_type = SurveyType.find(params[:id])
  end

  # POST /survey_types
  # POST /survey_types.json
  def create
    @survey_type = SurveyType.new(params[:survey_type])

    respond_to do |format|
      if @survey_type.save
        format.html { redirect_to @survey_type, notice: 'Survey type was successfully created.' }
        format.json { render json: @survey_type, status: :created, location: @survey_type }
      else
        format.html { render action: "new" }
        format.json { render json: @survey_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /survey_types/1
  # PUT /survey_types/1.json
  def update
    @survey_type = SurveyType.find(params[:id])

    respond_to do |format|
      if @survey_type.update_attributes(params[:survey_type])
        format.html { redirect_to @survey_type, notice: 'Survey type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_types/1
  # DELETE /survey_types/1.json
  def destroy
    @survey_type = SurveyType.find(params[:id])
    @survey_type.destroy

    respond_to do |format|
      format.html { redirect_to survey_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/survey_types_helper.rb
module SurveyTypesHelper
end

app/views/survey_types/_form.html.erb
<%= form_for(@survey_type) do |f| %>
  <% if @survey_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey_type.errors.count, "error") %> prohibited this survey_type from being saved:</h2>

      <ul>
      <% @survey_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_name %><br />
    <%= f.text_field :type_name %>
  </div>
  <div class="field">
    <%= f.label :need_option %><br />
    <%= f.check_box :need_option %>
  </div>
  <div class="field">
    <%= f.label :type_for %><br />
    <%= f.text_field :type_for %>
  </div>
  <div class="field">
    <%= f.label :type_data %><br />
    <%= f.text_field :type_data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/survey_types/edit.html.erb
<h1>Editing survey_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey_type %> |
<%= link_to 'Back', survey_types_path %>

app/views/survey_types/index.html.erb
<h1>Listing survey_types</h1>

<table>
  <tr>
    <th>Type name</th>
    <th>Need option</th>
    <th>Type for</th>
    <th>Type data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @survey_types.each do |survey_type| %>
  <tr>
    <td><%= survey_type.type_name %></td>
    <td><%= survey_type.need_option %></td>
    <td><%= survey_type.type_for %></td>
    <td><%= survey_type.type_data %></td>
    <td><%= link_to 'Show', survey_type %></td>
    <td><%= link_to 'Edit', edit_survey_type_path(survey_type) %></td>
    <td><%= link_to 'Destroy', survey_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Survey type', new_survey_type_path %>

app/views/survey_types/new.html.erb
<h1>New survey_type</h1>

<%= render 'form' %>

<%= link_to 'Back', survey_types_path %>

app/views/survey_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type name:</b>
  <%= @survey_type.type_name %>
</p>

<p>
  <b>Need option:</b>
  <%= @survey_type.need_option %>
</p>

<p>
  <b>Type for:</b>
  <%= @survey_type.type_for %>
</p>

<p>
  <b>Type data:</b>
  <%= @survey_type.type_data %>
</p>


<%= link_to 'Edit', edit_survey_type_path(@survey_type) %> |
<%= link_to 'Back', survey_types_path %>