config/routes.rb
CustomSurveyApp::Application.routes.draw do
  resources :survey_types

  resources :submission_entries

  resources :submissions

  devise_for :users

  resources :answers

  resources :questions

  resources :survey_records
  
  get "/home/survey_session"
  
  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end
  
  get "/home/error_survey"

  
    get "/:name" => "home#survey_session"
  
   root :to => 'home#survey_view'

end

app/models/survey_record.rb
class SurveyRecord < ActiveRecord::Base
  attr_accessible :description, :message, :name, :url,:status
  
  STATUS_UNPUB     = "unpublished"
  STATUS_PUBLISHED   = "published"
  
  has_many :questions,:dependent => :delete_all
  has_many :submissions,:dependent => :delete_all
  
  validates :name ,:uniqueness => true,  :presence =>true
  validates :url, :uniqueness => true, :presence => true
  validates :status , :presence=>true
  validates_format_of :url, :with => /^[a-zA-Z\d]*$/i,
        :message => "can only contain letters and numbers."
      
  validates :message, :presence => true
  validates :description , :presence => true
  
  def self.getStatusMap
    status_hash = Hash.new
    status_hash["unpublished"] = "unpublished"
    status_hash["published"] = "published"
    
    status_hash
  end
  
end

app/controllers/survey_records_controller.rb
class SurveyRecordsController < ApplicationController
  
  # GET /survey_records
  # GET /survey_records.json
  before_filter :auth_user, :except => [:index]
  load_and_authorize_resource 
   
  def index
    
    @survey_records = SurveyRecord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @survey_records }
    end
  end

  # GET /survey_records/1
  # GET /survey_records/1.json
  def show
    @survey_record = SurveyRecord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey_record }
    end
  end

  # GET /survey_records/new
  # GET /survey_records/new.json
  def new
    @survey_record = SurveyRecord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey_record }
    end
  end

  # GET /survey_records/1/edit
  def edit
    
    @survey_record = SurveyRecord.find(params[:id])
    
    @questions = @survey_record.questions.order("record_order asc")
        
    if @questions[0].nil?
      record_order = 1
    else
      record_order = @questions[@questions.size()-1].record_order + 1
    end
    
    @question = @survey_record.questions.new
    @question.record_order = record_order 
    
  end

  # POST /survey_records
  # POST /survey_records.json
  def create
    @survey_record = SurveyRecord.new(params[:survey_record])
    
    @questions = @survey_record.questions.order("record_order asc")
    
    if @questions[0].nil?
      record_order = 1
    else
      record_order = @questions[@questions.size()-1].record_order + 1
    end
    
    if @survey_record.url.nil? || @survey_record.url == ""
      url = @survey_record.name
      url[" "] = "_"
      @survey_record.url = @survey_record.name
    end
    
    respond_to do |format|
      if @survey_record.save
        
        @question = @survey_record.questions.new
        @question.record_order = record_order 
        
        format.html { render action: "edit", notice: 'Survey record was successfully created.' }
        format.json { render json: @survey_record, status: :created, location: @survey_record }
        format.js
      else
        puts @survey_record.errors.full_messages
        format.html { render action: "new" }
        format.json { render json: @survey_record.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /survey_records/1
  # PUT /survey_records/1.json
  def update
    @survey_record = SurveyRecord.find(params[:id])
    
    @questions = @survey_record.questions.order("record_order asc");
    @question = Question.new
    @question.survey_record_id = @survey_record.id
    
    if @questions[0].nil?
      record_order = 1
    else
      record_order = @questions[@questions.size()-1].record_order + 1
    end
    
    @question.record_order = record_order

    respond_to do |format|
      if @survey_record.update_attributes(params[:survey_record])
        @success = "Survey Record Successfully updated"
        format.html { redirect_to @survey_record, notice: 'Survey record was successfully updated.' }
        format.json { head :no_content }
        format.js 
      else
        errorMsg = ""
        
        @survey_record.errors.full_messages.each do |key, value| 
               errorMsg = errorMsg+key.to_s+"--"+value.to_s   
        end          
        
        @error = errorMsg
        format.html { render action: "edit" }
        format.json { render json: @survey_record.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /survey_records/1
  # DELETE /survey_records/1.json
  def destroy
    @survey_record = SurveyRecord.find(params[:id])
    @survey_record.destroy 
    
    respond_to do |format|
      format.html { redirect_to survey_records_url ,notice: " Survey Record successfully deleted"}
      format.json { head :no_content }
    end
  end
end

app/helpers/survey_records_helper.rb
module SurveyRecordsHelper
end

app/views/survey_records/_form.html.erb
<%= form_for(@survey_record,:html=>{:class=>"form-horizontal survey-form"},:remote=>true) do |f| %>
  <% if @survey_record.errors.any? %>
       <%  @survey_record.errors.full_messages.each do |key, value| %>
                  <div class="error"><%= key %> <%= value %></div>
          <%  end%>
    <% end %>

  <fieldset>  
    <div class="control-group">
      <div class="label-form">Survey Heading</div>         
      <%= f.text_field :name,:class=>"span12 required",:placeholder=>"Survey Heading" %>
    </div>

    <div class="control-group">
      <div class="label-form">Survey Description</div>   
      <%= f.text_area  :description,:rows=>"4", :cols=>"50",:class=>"span12 required",:placeholder=>"Survey Description" %>

    </div>

    <div class="control-group">          
      <div class="label-form">URL to display survey e.g. "example" will create survey-fy.herokuapp.com/example</div>         
      <%= f.text_field :url, :class=>"span12",:placeholder=>"URL to assign, default -- Survey Title" %>
    </div>
    
    <div class="control-group">     
      <div class="label-form">Message on submission</div>       
      <%= f.text_field :message,:class=>"span12 required",:placeholder=>"Message to be displayed after submitting survey"%>
     </div>
    
    <div class="control-group">      
      
      <div class="label-form width220">Survey Status</div>
      <% if @survey_record.status.nil? %>
        <% status = SurveyRecord::STATUS_UNPUB  %>
      <%else%>
        <% status = @survey_record.status  %>
      <%end%>
      
      <%= f.select :status ,options_for_select(SurveyRecord.getStatusMap,selected = status) %>
    </div>
    
    <div class="control-group">
      <% if !@survey_record.name.nil? %>
        <%= f.submit "Update Survey" ,:class=>"btn btn-primary" %>
      <%else%>
        <%= f.submit "Create Survey" ,:class=>"btn btn-primary" %>
      <%end%>
    </div>
  </fieldset>
<% end %>

<script>
  $(".survey-form").validate();
  
</script>

app/views/survey_records/create.js.erb
<% if !@survey_record.id.nil? %>
  document.location.href = "/survey_records/"+"<%=@survey_record.id.to_s%>"+"/edit";
  <% else %>
  
   <% firstMessage = @survey_record.errors.full_messages[0]%>
       $("#errorMessage").html("<%=firstMessage%>");
       schedule_notification_hider();
   
<%end%>

app/views/survey_records/edit.html.erb
<div class="row-fluid generic-heading">
  <div class="container">
    <h3 class="span5" style="margin-top:0;margin-bottom:0">Edit Survey
      <div class="label moveUp5" id="lable_status">
          <%=@survey_record.status%>
        </div></h3>
    <div class="span7">
      <ul class="horizontal-list pull-right marginTop3">
        <li><%= link_to ' ', new_survey_record_path,:method=>"get",:class=>"icon-custom-add icon-big", :title=>"Create New Survey" %>
        </li>
        <li>
           <%= link_to ' ', @survey_record, method: :delete, data: { confirm: 'Are you sure to delete'+ @survey_record.name+'?' },:class=>"icon-custom-delete icon-big" %>
        </li>
        <li><%= link_to ' ', survey_records_path, :class=>"icon-custom-list icon-big", :title=>"Show all Existing Surveys" %>  </li>
      </ul>
    </div>
  </div>
</div>



<div class="container">
  
  <div class="row-fluid">

    <%= render 'form' %>

  </div>
  <hr class="divider">
  <h4>Questions</h4>
  
<div class="row-fluid">
  <div class="span7" id="all_ques">
    <%= render(:partial => "questions/index")%>
  </div>
  <div class="span5" id="ques_form">
    <%= render "questions/form" %>
  </div>

</div>
  
</div>

<script>
      
   
</script>

app/views/survey_records/index.html.erb
<div class="row-fluid generic-heading">
  <div class="container">
    <h3 class="span5">Existing Survey</h3>
    <div class="span7">
      <ul class="horizontal-list pull-right">
        <li>
          <%= link_to "New Survey Record", new_survey_record_path, :class=>'btn btn-medium btn-info', :title=>"Create New Survey" %>
        </li>      			      				 			      			
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <table class="table-bordered table">
    <% @survey_records.each do |survey_record| %>
      <tr>
        <td class="span9">
             <% if survey_record.url.nil? || survey_record.url == "" %>
              <%    url = survey_record.name
                else 
                    url = survey_record.url%>
              <% end%>
             <a href=<%="/"+url%> title="<%=survey_record.name%>">
              <%= survey_record.name %> at <em class="lightGray"><%=url%></em>   
             </a>
          <% if survey_record.status == "published" %>
          <div class="label-success label">P</div>
          <%else%>
            <div class="label-warning label">U</div>
          <%end%>
        </td>
        <td class="span1 text-center">
          <%= link_to " ", edit_survey_record_path(survey_record),:class=>'icon-pencil', :title=>"Edit Survey" %>
        </td>
        <td class="span1 text-center">
            <%=link_to " ",submissions_path(:survey_id=>survey_record.id),
            :class=>"icon-eye-open", :title=>"Show Survey" %>
        </td>
        <td class="span1 text-center">
          <%= link_to ' ', survey_record, method: :delete, data: { confirm: 'All Reports linked with this survey will also be deleted , Are you sure to delete '+survey_record.name+'?' },
            :class=>"icon-trash" , :title=>"Delete Survey"%>
        </td>

      </tr>

    <% end %>

  </table>
  <hr>

app/views/survey_records/new.html.erb
<div class="row-fluid generic-heading">
  <div class="container">
	<h3 class="span5">Create New Survey</h3>
    <div class="span7">
      <ul class="horizontal-list pull-right">
        <li>
          <%= link_to ' ', survey_records_path, :class=>'icon-custom-list icon-big', :title=>"Show all existing surveys" %>
        </li>      			      				 			      			
      </ul>
    </div>
    
  </div>   
</div>

  <div class="container">
    <%= render 'form' %>    
   </div>

app/views/survey_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @survey_record.name %>
</p>

<p>
  <b>Description:</b>
  <%= @survey_record.description %>
</p>

<p>
  <b>Url:</b>
  <%= @survey_record.url %>
</p>

<p>
  <b>Message:</b>
  <%= @survey_record.message %>
</p>


<%= link_to 'Edit', edit_survey_record_path(@survey_record) %> |
<%= link_to 'Back', survey_records_path %>

app/views/survey_records/update.js.erb
<% if @survey_record.nil? %>

  

<% else !@survey_record.nil? %>  

    $("#all_ques").html("<%=  escape_javascript(render(:partial => "questions/index"))%>");
    $("#lable_status").html("<%= @survey_record.status %>");
  
<%end%>
    
    <% if !@error.nil? %>
      $("#errorMessage").html("<%=@error%>");
      

    <% end %>
      
    <% if !@success.nil? %>  
      $("#successMessage").html("<%=@success%>");
    <%end%>  
      
      schedule_notification_hider();