config/routes.rb
CustomSurveyApp::Application.routes.draw do
  resources :survey_types

  resources :submission_entries

  resources :submissions

  devise_for :users

  resources :answers

  resources :questions

  resources :survey_records
  
  get "/home/survey_session"
  
  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end
  
  get "/home/error_survey"

  
    get "/:name" => "home#survey_session"
  
   root :to => 'home#survey_view'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :marks, :name, :qusestion_id, :record_order
  
  validates :name,:presence => true
  validates :record_order, :presence=>true
  
  validates_with AnswerValidator

  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  load_and_authorize_resource
     before_filter :authenticate_user!

  
  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :qusestion_id %><br />
    <%= f.number_field :qusestion_id %>
  </div>
  <div class="field">
    <%= f.label :record_order %><br />
    <%= f.number_field :record_order %>
  </div>
  <div class="field">
    <%= f.label :marks %><br />
    <%= f.number_field :marks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Qusestion</th>
    <th>Record order</th>
    <th>Marks</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= answer.name %></td>
    <td><%= answer.qusestion_id %></td>
    <td><%= answer.record_order %></td>
    <td><%= answer.marks %></td>
    <td><%= link_to 'Show', answer %></td>
    <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @answer.name %>
</p>

<p>
  <b>Qusestion:</b>
  <%= @answer.qusestion_id %>
</p>

<p>
  <b>Record order:</b>
  <%= @answer.record_order %>
</p>

<p>
  <b>Marks:</b>
  <%= @answer.marks %>
</p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>